name: "Upload cache"
description: "Custom upload action"
inputs:
  key:
    description: "Cache key"
    required: true
  path:
    description: "A directory or file to upload"
    required: true
  folder:
    description: "S3 subfolder"
    default: cache
    required: false
  override:
    description: "Allow force upload existing cache"
    default: false
    required: false

runs:
  using: "composite"
  steps:
    - name: Prepare cache
      shell: bash -euxo pipefail {0}
      env:
        SOURCE: ${{ inputs.path }}
        ARCHIVE: /tmp/uploads/${{ inputs.key }}.tar.zst
      run: |
        mkdir -p $(dirname $ARCHIVE)
        echo "" > manifest.txt
        echo "" > ignore.txt
        
        for i in ${SOURCE} 
        do
          echo "$i" >> manifest.txt
        done
        
        # split excluded folders to ignore.txt
        sed -i -e '/^!/{w ignore.txt' -e 'd}' manifest.txt
        
        # remove leading '!' identifier
        sed -i -e 's/^.//' ignore.txt
        
        # remove each excluded folder listed
        while IFS= read -r line; do
          rm -rf "$line"
        done <ignore.txt

        time /bin/tar --posix --use-compress-program zstdmt -cf ${ARCHIVE} --exclude manifest.txt --exclude ignore.txt -P -C ${GITHUB_WORKSPACE} --files-from manifest.txt

    - name: Upload cache
      shell: bash -euxo pipefail {0}
      env:
        ARCHIVE: /tmp/uploads/${{ inputs.key }}.tar.zst
        OVERRIDE: ${{ inputs.override }}
        FOLDER: ${{ inputs.folder }}
        BUCKET: neon-github-dev
      run: |
        FILENAME=$(basename $ARCHIVE)
        FILESIZE=$(du -sh ${ARCHIVE} | cut -f1)
        
        echo "${FILENAME} - ${FILESIZE}" >> ${GITHUB_STEP_SUMMARY}
        
        S3_KEY=$(aws s3api list-objects-v2 --bucket ${BUCKET} --prefix ${FOLDER} | jq -r '.Contents[].Key' | grep ${FILENAME} | tail -1 || true)
        if [ -z "${S3_KEY}" ]; then
          echo "uploading cache"
          time aws s3 mv --only-show-errors ${ARCHIVE} s3://${BUCKET}/${FOLDER}/${FILENAME}
          else
            if [ "${OVERRIDE}" = "true" ]; then
              echo "override existing cache"
              time aws s3 mv --only-show-errors ${ARCHIVE} s3://${BUCKET}/${FOLDER}/${FILENAME}
            else
              echo "cache exists, skipping upload"
          fi
        fi
