name: "Download cache"
description: "Custom download action"
inputs:
  key:
    description: "Cache key"
    required: true
  path:
    description: "A directory to put cache into"
    default: "."
    required: false
  folder:
    description: "S3 subfolder"
    default: cache
    required: false

runs:
  using: "composite"
  steps:
    - name: Download cache
      id: download-cache
      shell: bash -euxo pipefail {0}
      env:
        BUCKET: neon-github-dev
        FOLDER: ${{ inputs.folder }}
        TARGET: ${{ inputs.path }}
        KEY: ${{ inputs.key }}
        TEMPDIR: /tmp/downloads
        EXT: tar.zst
      run: |
        for i in ${KEY} 
        do
          S3_KEY=$(aws s3api list-objects-v2 --bucket ${BUCKET} --prefix ${FOLDER} | jq -r '.Contents[].Key' | grep "$i" | tail -1 || true)  
          if [ -z "${S3_KEY}" ]; then
            echo "no hit on provided cache key"
          else
            time aws s3 cp --only-show-errors s3://${BUCKET}/${FOLDER}/"$i".${EXT} ${TEMPDIR}/"$i".${EXT}
            time /bin/tar --use-compress-program unzstd -xf ${TEMPDIR}/"$i".${EXT} -P -C ${GITHUB_WORKSPACE}
            exit 0
          fi
        done
